/* El Héroe de las Palabras — motor Canvas sin dependencias */
(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const W=960,H=600,SAVE_KEY='verbalia_save_v2',RANK_KEY='verbalia_ranking_v2',data=GAME_DATA;
const keys={}, pressed=new Set(); let last=0, running=false, paused=false, modalOpen=false, dialogueOpen=false, sound=true, selectedColor='#52d6ff';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rand=(a,b)=>a+Math.random()*(b-a);
const wordByEs=es=>data.words.find(w=>w.es.toLocaleLowerCase()===es.toLocaleLowerCase());
let state,player,entities=[],particles=[],projectiles=[],currentDialogue=null,dialogueIndex=0,nearEntity=null;
const freshState=name=>({name:name||'Héroe',color:selectedColor,region:0,x:330,y:350,hp:100,maxHp:100,mana:60,maxMana:60,coins:8,xp:0,level:1,learned:[],inventory:[{id:'potion',qty:1}],kills:0,shadowKills:0,bosses:[],completed:[],quest:'meetOwl',questKills:0,sword:1,armor:0,playtime:0,started:Date.now()});
function save(show=false){if(!state)return;state.x=player.x;state.y=player.y;localStorage.setItem(SAVE_KEY,JSON.stringify(state));updateRanking();if(show)toast('Partida guardada · Игра сохранена','💾')}
function load(){try{return JSON.parse(localStorage.getItem(SAVE_KEY))}catch{return null}}
function updateRanking(){let rows=[];try{rows=JSON.parse(localStorage.getItem(RANK_KEY))||[]}catch{} const row={name:state.name,words:state.learned.length,coins:state.coins,level:state.level,score:state.learned.length*100+state.kills*20+state.coins+state.bosses.length*500,date:Date.now()};const old=rows.findIndex(r=>r.name===state.name);if(old>=0)rows[old]=row;else rows.push(row);rows.sort((a,b)=>b.score-a.score);localStorage.setItem(RANK_KEY,JSON.stringify(rows.slice(0,20)))}
class Player{constructor(){this.x=state.x;this.y=state.y;this.r=16;this.speed=170;this.dir={x:1,y:0};this.attacking=0;this.attackCd=0;this.dash=0;this.dashCd=0;this.hurt=0}
 update(dt){let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);if(dx||dy){let l=Math.hypot(dx,dy);dx/=l;dy/=l;this.dir={x:dx,y:dy}}let speed=this.speed*(this.dash>0?2.8:1);this.x=clamp(this.x+dx*speed*dt,12,W-12);this.y=clamp(this.y+dy*speed*dt,88,H-13);if(this.attackCd>0)this.attackCd-=dt;if(this.attacking>0)this.attacking-=dt;if(this.dash>0)this.dash-=dt;if(this.dashCd>0)this.dashCd-=dt;if(this.hurt>0)this.hurt-=dt;if(pressed.has('Space'))this.attack();if((pressed.has('ShiftLeft')||pressed.has('ShiftRight'))&&this.dashCd<=0){this.dash=.18;this.dashCd=1;burst(this.x,this.y,'#8ceaff',10)}if(this.x<=13&&state.region>0){changeRegion(state.region-1,W-45,this.y)}else if(this.x>=W-13&&state.region<2){changeRegion(state.region+1,45,this.y)}}
 attack(){if(this.attackCd>0)return;this.attackCd=.38;this.attacking=.16;sfx(180,.06,'square');const hx=this.x+this.dir.x*31,hy=this.y+this.dir.y*31;entities.filter(e=>e.type==='enemy'&&!e.dead&&Math.hypot(e.x-hx,e.y-hy)<37+e.r).forEach(e=>e.damage(22+state.sword*7,this.dir));burst(hx,hy,'#fff1a6',5)}
 damage(n){if(this.hurt>0||this.dash>0)return;let dmg=Math.max(1,n-state.armor*2);state.hp-=dmg;this.hurt=.8;burst(this.x,this.y,'#ff6577',10);sfx(90,.12,'sawtooth');if(state.hp<=0){state.hp=state.maxHp;state.coins=Math.max(0,state.coins-5);this.x=150;this.y=330;toast('Has despertado en el pueblo · Ты очнулся в деревне','💔');changeRegion(0,150,330)}updateHud()}
 draw(){ctx.save();ctx.translate(this.x,this.y);if(this.hurt>0&&Math.floor(this.hurt*12)%2)ctx.globalAlpha=.35;if(this.dash>0)ctx.globalAlpha=.55;ctx.fillStyle='#16152c';ctx.fillRect(-13,-13,26,28);ctx.fillStyle=state.color;ctx.fillRect(-11,-18,22,25);ctx.fillStyle='#f6cda9';ctx.fillRect(-7,-14,14,11);ctx.fillStyle='#202035';ctx.fillRect(this.dir.x>=0?3:-6,-10,3,3);ctx.fillStyle='#69452f';ctx.fillRect(-13,7,10,10);ctx.fillRect(3,7,10,10);if(this.attacking>0){ctx.strokeStyle='#fff1ac';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(this.dir.x*14,this.dir.y*14);ctx.lineTo(this.dir.x*47,this.dir.y*47);ctx.stroke()}ctx.restore()}}
class Enemy{constructor(x,y,opt={}){Object.assign(this,{x,y,type:'enemy',r:15,hp:45,maxHp:45,speed:45,damageVal:10,color:'#62385e',name:'Sombra de Tinta',weak:'hola',boss:false,dead:false,hit:0,cool:0},opt)}
 update(dt){if(this.dead)return;this.hit=Math.max(0,this.hit-dt);this.cool-=dt;let d=dist(this,player);if(d<260&&d>this.r+player.r){this.x+=(player.x-this.x)/d*this.speed*dt;this.y+=(player.y-this.y)/d*this.speed*dt}if(d<this.r+player.r+4&&this.cool<=0){player.damage(this.damageVal);this.cool=1.1}if(this.boss&&Math.random()<dt*.8){let a=Math.atan2(player.y-this.y,player.x-this.x);projectiles.push({x:this.x,y:this.y,vx:Math.cos(a)*130,vy:Math.sin(a)*130,r:6,life:3,enemy:true,color:'#8c65a8',damage:8})}}
 damage(n,dir,magic=''){if(this.dead)return;if(magic&&magic===this.weak)n*=2;this.hp-=n;this.hit=.12;this.x+=(dir?.x||0)*12;this.y+=(dir?.y||0)*12;burst(this.x,this.y,magic?'#6deaff':'#ffbf64',7);if(this.hp<=0)this.die()}
 die(){this.dead=true;let gain=this.boss?30:Math.floor(rand(3,8));state.coins+=gain;state.kills++;state.xp+=this.boss?80:15;for(let i=0;i<gain;i+=2)particles.push({x:this.x,y:this.y,vx:rand(-50,50),vy:rand(-90,-20),life:1,color:'#ffd34f',coin:true});if(!this.boss){
 state.shadowKills=(state.shadowKills||0)+1;
 state.questKills=Math.min(3,state.shadowKills);
 updateObjective();
 if(state.quest==='killShadows'&&state.shadowKills>=3)completeShadowQuest();
}if(this.boss){state.bosses.push(state.region);state.completed.push('boss');learnWord('luz');toast('¡Palabra Maestra: LUZ! · Главное слово: СВЕТ','💎')}levelCheck();updateHud();save()}
 draw(){if(this.dead)return;ctx.save();ctx.translate(this.x,this.y);if(this.hit)ctx.globalAlpha=.55;ctx.fillStyle=this.color;ctx.beginPath();ctx.arc(0,0,this.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-8,-5,5,5);ctx.fillRect(4,-5,5,5);ctx.fillStyle='#261a31';ctx.fillRect(-6,-4,2,3);ctx.fillRect(6,-4,2,3);if(this.boss){ctx.strokeStyle='#dcb4ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,this.r+4,0,Math.PI*2);ctx.stroke()}ctx.restore();if(this.hp<this.maxHp&&!this.boss){ctx.fillStyle='#171323';ctx.fillRect(this.x-18,this.y-this.r-10,36,5);ctx.fillStyle='#ef5670';ctx.fillRect(this.x-18,this.y-this.r-10,36*this.hp/this.maxHp,5)}}}
class NPC{constructor(x,y,id,name,portrait,color='#e1a45f'){Object.assign(this,{x,y,id,name,portrait,color,type:'npc',r:17})}update(){}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.fillStyle=this.color;ctx.fillRect(-13,-15,26,30);ctx.fillStyle='#f4c7a0';ctx.beginPath();ctx.arc(0,-17,11,0,Math.PI*2);ctx.fill();ctx.font='20px sans-serif';ctx.fillText(this.portrait,-11,8);ctx.restore();ctx.fillStyle='#18152ccc';ctx.fillRect(this.x-35,this.y+22,70,15);ctx.fillStyle='#fff';ctx.font='bold 10px sans-serif';ctx.textAlign='center';ctx.fillText(this.name,this.x,this.y+33);ctx.textAlign='left'}}
function spawnRegion(){entities=[];projectiles=[];const r=state.region;if(r===0){entities.push(new NPC(430,235,'owl','Don Diccionario','🦉','#76518e'),new NPC(700,370,'shop','Señor Moneda','🧔','#ac653c'));entities.push(new Enemy(805,180),new Enemy(730,500),new Enemy(560,445))}if(r===1){entities.push(new NPC(170,200,'ana','Ana','👩','#d9788c'));entities.push(new Enemy(370,180),new Enemy(620,270,{weak:'uno'}),new Enemy(780,470,{weak:'dos'}),new Enemy(430,480))}if(r===2){entities.push(new NPC(180,370,'family','Pablo','👦','#4b82b4'));entities.push(new Enemy(470,190),new Enemy(710,170),new Enemy(720,420),new Enemy(520,360,{r:33,hp:220,maxHp:220,speed:32,damageVal:16,color:'#484157',name:'Guardián Gris',weak:'luz',boss:true}))}updateRegionUI()}
function changeRegion(n,x,y){state.region=n;player.x=x;player.y=y;state.x=x;state.y=y;spawnRegion();toast(data.regions[n].name,data.regions[n].icon);save()}
function drawWorld(t){const r=data.regions[state.region];ctx.fillStyle=r.ground;ctx.fillRect(0,0,W,H);for(let y=80;y<H;y+=32)for(let x=0;x<W;x+=32){ctx.fillStyle=((x/32+y/32)%2)?r.tile:r.ground;ctx.fillRect(x,y,32,32);ctx.fillStyle='#ffffff08';ctx.fillRect(x+3,y+4,4,3)}ctx.fillStyle=r.edge;ctx.fillRect(0,72,W,14);ctx.fillRect(0,H-10,W,10);
 // decoraciones del mapa
 if(state.region===0){drawHouse(85,130,'#c45c50');drawHouse(700,110,'#d69a48');drawPond(195,430);for(let i=0;i<8;i++)drawTree(40+i*125,i%2?535:100)}
 if(state.region===1){for(let i=0;i<17;i++)drawTree((i*83)%920,100+(i*137)%450);ctx.fillStyle='#654b39';ctx.fillRect(0,325,960,45);ctx.fillStyle='#8c7350';ctx.fillRect(0,333,960,29)}
 if(state.region===2){drawHouse(75,120,'#805f9e');drawHouse(760,110,'#a75155');drawHouse(120,440,'#5c8b9d');ctx.fillStyle='#76627c';ctx.fillRect(390,90,260,180);ctx.fillStyle='#251f35';ctx.fillRect(493,190,55,80)}
 // flechas de transición
 if(state.region>0){ctx.fillStyle='#fff8';ctx.font='30px sans-serif';ctx.fillText('‹',8,330)}if(state.region<2){ctx.fillText('›',935,330)}
 entities.forEach(e=>e.draw());projectiles.forEach(drawProjectile);particles.forEach(drawParticle);player.draw();if(nearEntity){ctx.strokeStyle='#ffe064';ctx.lineWidth=2;ctx.beginPath();ctx.arc(nearEntity.x,nearEntity.y,nearEntity.r+9+Math.sin(t/180)*2,0,Math.PI*2);ctx.stroke()}}
function drawTree(x,y){ctx.fillStyle='#3e3224';ctx.fillRect(x-5,y,10,25);ctx.fillStyle='#295b39';ctx.beginPath();ctx.arc(x,y-4,24,0,Math.PI*2);ctx.fill();ctx.fillStyle='#397848';ctx.beginPath();ctx.arc(x-8,y-12,15,0,Math.PI*2);ctx.fill()}
function drawHouse(x,y,c){ctx.fillStyle='#6b4936';ctx.fillRect(x,y,130,85);ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(x-15,y);ctx.lineTo(x+65,y-55);ctx.lineTo(x+145,y);ctx.fill();ctx.fillStyle='#352535';ctx.fillRect(x+52,y+38,30,47);ctx.fillStyle='#9de0ef';ctx.fillRect(x+12,y+20,25,22)}function drawPond(x,y){ctx.fillStyle='#4ba9b5';ctx.beginPath();ctx.ellipse(x,y,85,45,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#80e0cc';ctx.stroke()}
function burst(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-80,80),vy:rand(-80,50),life:rand(.3,.8),color})}function drawParticle(p){ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.color;if(p.coin){ctx.font='14px sans-serif';ctx.fillText('●',p.x,p.y)}else ctx.fillRect(p.x,p.y,4,4);ctx.globalAlpha=1}function drawProjectile(p){ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
function update(dt){if(paused||modalOpen||dialogueOpen)return;state.playtime+=dt;state.mana=clamp(state.mana+7*dt,0,state.maxMana);player.update(dt);entities.forEach(e=>e.update(dt));nearEntity=entities.filter(e=>e.type==='npc'&&dist(e,player)<65).sort((a,b)=>dist(a,player)-dist(b,player))[0]||null;$('#interact-hint').classList.toggle('hidden',!nearEntity);if(nearEntity)$('#interact-text').textContent=nearEntity.id==='shop'?'Hablar / Comprar':'Hablar';if(pressed.has('KeyE')||pressed.has('Enter'))nearEntity?interact(nearEntity):openMagic();if(pressed.has('KeyQ'))openMagic();updateProjectiles(dt);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);if(pressed.has('KeyD'))openModal('dictionary');if(pressed.has('KeyI'))openModal('inventory');if(pressed.has('KeyJ'))openModal('journal');if(pressed.has('KeyP'))togglePause();updateHud()}
function updateProjectiles(dt){projectiles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.enemy&&dist(p,player)<p.r+player.r){player.damage(p.damage);p.life=0}else if(!p.enemy){entities.filter(e=>e.type==='enemy'&&!e.dead).forEach(e=>{if(dist(p,e)<p.r+e.r){e.damage(p.damage,{x:p.vx/220,y:p.vy/220},p.word);p.life=0}})}});projectiles=projectiles.filter(p=>p.life>0&&p.x>-20&&p.x<W+20&&p.y>60&&p.y<H+20)}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);drawWorld(t);pressed.clear();requestAnimationFrame(loop)}
function interact(n){if(n.id==='shop'){startDialogue('shop',()=>openShop())}else{startDialogue(n.id);if(n.id==='owl'&&state.quest==='meetOwl'){
 if(!state.completed.includes('meetOwl'))state.completed.push('meetOwl');
 state.quest='killShadows';
 state.shadowKills=state.shadowKills||0;
 state.questKills=Math.min(3,state.shadowKills);
 if(state.shadowKills>=3)completeShadowQuest();
 else { updateObjective(); save(); }
}}}
function startDialogue(id,after=null){currentDialogue={lines:data.dialogues[id],after};dialogueIndex=0;dialogueOpen=true;showDialogueLine();$('#dialogue').classList.remove('hidden')}
function showDialogueLine(){const l=currentDialogue.lines[dialogueIndex];$('#speaker').textContent=l.speaker;$('#speaker-portrait').textContent=l.portrait;$('#dialogue-ru').textContent=l.ru;$('#dialogue-ru').classList.add('hidden');let html=escapeHtml(l.text);l.keys.sort((a,b)=>b.length-a.length).forEach(k=>{const w=wordByEs(k);if(w){learnWord(k);const re=new RegExp(escapeRegex(k),'i');html=html.replace(re,m=>`<span class="key-word" data-word="${w.id}">${m}</span>`)}});$('#dialogue-text').innerHTML=html;bindWordTips();updateHud();save()}
function nextDialogue(){if(!currentDialogue)return;if(++dialogueIndex<currentDialogue.lines.length)showDialogueLine();else{let cb=currentDialogue.after;$('#dialogue').classList.add('hidden');$('#word-tip').classList.add('hidden');dialogueOpen=false;currentDialogue=null;if(cb)cb();updateObjective()}}
function learnWord(es){const w=wordByEs(es);if(w&&!state.learned.includes(w.id)){state.learned.push(w.id);toast(`Nueva palabra: ${w.es} — ${w.ru}`,w.icon);sfx(620,.12,'sine')}}
function bindWordTips(){$$('.key-word').forEach(el=>{const show=()=>{const w=data.words.find(x=>x.id===el.dataset.word),box=el.getBoundingClientRect(),tip=$('#word-tip');tip.innerHTML=`<strong>${w.icon} ${w.es}</strong><b> — ${w.ru}</b><small>${w.example}</small>`;tip.style.left=`${clamp(box.left,10,innerWidth-250)}px`;tip.style.top=`${Math.max(10,box.top-95)}px`;tip.classList.remove('hidden')};el.onmouseenter=show;el.onclick=show;el.onmouseleave=()=>$('#word-tip').classList.add('hidden')})}
function cast(word){if(state.mana<15)return toast('No tienes maná · Недостаточно маны','💧');state.mana-=15;let speed=260;projectiles.push({x:player.x+player.dir.x*22,y:player.y+player.dir.y*22,vx:player.dir.x*speed,vy:player.dir.y*speed,r:9,life:2,enemy:false,color:word.es==='fuego'?'#ff7a3d':'#62e8ff',damage:25,word:word.es});burst(player.x,player.y,'#80f4ff',9);sfx(450,.16,'sine');closeModal();updateHud()}
function completeShadowQuest(){
 if(!state.completed.includes('killShadows'))state.completed.push('killShadows');
 state.quest='boss';
 state.questKills=3;
 toast('¡Misión completada! Viaja a la Aldea de la Familia.','📜');
 updateObjective();
 save();
}
function levelCheck(){let need=state.level*60;if(state.xp>=need){state.xp-=need;state.level++;state.maxHp+=10;state.hp=state.maxHp;state.maxMana+=5;toast(`¡Nivel ${state.level}! · Уровень ${state.level}`,'⭐')}}
function openModal(kind){if(!running&&!['help','ranking'].includes(kind))return;modalOpen=true;paused=false;$('#pause').classList.add('hidden');$('#modal-backdrop').classList.remove('hidden');const m={dictionary:['COLECCIÓN DE PALABRAS','Mi Diccionario'],inventory:['EQUIPO Y OBJETOS','Mi Mochila'],journal:['AVENTURAS DE VERBALIA','Mis Misiones'],ranking:['HÉROES DE VERBALIA','Clasificación'],help:['GUÍA DEL AVENTURERO','Cómo jugar'],magic:['PODER DE LAS PALABRAS','Magia de palabras']}[kind];$('#modal-kicker').textContent=m[0];$('#modal-title').textContent=m[1];renderModal(kind)}
function closeModal(){modalOpen=false;$('#modal-backdrop').classList.add('hidden')}
function renderModal(kind){const c=$('#modal-content');if(kind==='dictionary'){let active=data.themes.find(t=>t.words.some(w=>state.learned.includes(w.id)))?.id||'saludos';const render=id=>{c.innerHTML=`<div class="tabs">${data.themes.map(t=>`<button data-theme="${t.id}" class="${id===t.id?'active':''}">${t.icon} ${t.name}</button>`).join('')}</div><div class="word-grid">${data.themes.find(t=>t.id===id).words.map(w=>state.learned.includes(w.id)?`<article class="word-card"><span class="emoji">${w.icon}</span><div><strong>${w.es}</strong><b>${w.ru}</b><p>${w.example}</p></div></article>`:`<article class="word-card locked"><span class="emoji">🔒</span><div><strong>???</strong><b>Не открыто</b><p>Descubre esta palabra en Verbalia.</p></div></article>`).join('')}</div>`;$$('[data-theme]').forEach(b=>b.onclick=()=>render(b.dataset.theme))};render(active)}
if(kind==='inventory')c.innerHTML=`<div class="inventory-grid">${state.inventory.length?state.inventory.map(i=>{let d=data.items[i.id];return `<article class="item"><div class="emoji">${d.icon}</div><strong>${d.name}</strong><p>${d.ru}</p><b>× ${i.qty}</b>${i.id==='potion'?'<button data-use="potion">Usar</button>':''}</article>`}).join(''):'<p>Tu mochila está vacía. · Твой рюкзак пуст.</p>'}</div>`,$$('[data-use]').forEach(b=>b.onclick=usePotion);
if(kind==='journal'){let quests=[['meetOwl','Habla con Don Diccionario','Поговори с Доном Словарём'],['killShadows','Derrota 3 Sombras de Tinta',`Победи 3 Чернильные Тени (${state.questKills}/3)`],['boss','Derrota al Guardián Gris','Победи Серого Стража']];c.innerHTML=quests.map((q,i)=>`<article class="quest ${state.completed.includes(q[0])?'done':''}"><h3>${state.completed.includes(q[0])?'✓':state.quest===q[0]?'◆':'○'} ${q[1]}</h3><p>${q[2]}</p><small>${state.completed.includes(q[0])?'Completada':state.quest===q[0]?'Misión actual':'Bloqueada'}</small></article>`).join('')}
if(kind==='ranking'){let rows=[];try{rows=JSON.parse(localStorage.getItem(RANK_KEY))||[]}catch{};c.innerHTML=`<div class="ranking-row"><b>#</b><b>Héroe</b><b>Nivel</b><b>Palabras</b><b>Puntos</b></div>${rows.map((r,i)=>`<div class="ranking-row ${r.name===state?.name?'me':''}"><b>${i<3?['🥇','🥈','🥉'][i]:i+1}</b><strong>${escapeHtml(r.name)}</strong><span>${r.level}</span><span>${r.words}</span><span>${r.score}</span></div>`).join('')||'<p>Aún no hay héroes. · Героев пока нет.</p>'}`}
if(kind==='help')c.innerHTML=`<div class="help-grid"><div>Mover · Двигаться <kbd>WASD / ↑↓←→</kbd></div><div>Atacar · Атака <kbd>ESPACIO / CLIC</kbd></div><div>Hablar · Говорить <kbd>E / ENTER</kbd></div><div>Rodar · Рывок <kbd>SHIFT</kbd></div><div>Diccionario · Словарь <kbd>D</kbd></div><div>Mochila · Рюкзак <kbd>I</kbd></div><div>Misiones · Задания <kbd>J</kbd></div><div>Magia · Магия <kbd>Q</kbd></div><div>Pausa · Пауза <kbd>P</kbd></div><div>Traducción · Перевод <kbd>T</kbd></div></div><p>Acércate a las personas y pulsa E. Las palabras doradas muestran su traducción rusa.</p>`;
if(kind==='magic'){let magic=data.words.filter(w=>['hola','uno','dos','fuego','agua','luz'].includes(w.es)&&state.learned.includes(w.id));c.innerHTML=`<p>Elige una palabra (15 maná). · Выбери слово (15 маны).</p><div class="magic-list">${magic.map(w=>`<button class="magic-button" data-spell="${w.id}" ${state.mana<15?'disabled':''}><strong>${w.icon} ${w.es}</strong>${w.ru}</button>`).join('')||'<p>Aprende una palabra mágica primero.</p>'}</div>`;$$('[data-spell]').forEach(b=>b.onclick=()=>cast(data.words.find(w=>w.id===b.dataset.spell)))} }
function openMagic(){openModal('magic')}
function openShop(){openModal('inventory');$('#modal-kicker').textContent='TIENDA · МАГАЗИН';$('#modal-title').textContent='El Rincón de Moneda';let c=$('#modal-content');c.innerHTML=`<p>Tienes 🪙 <b>${state.coins}</b></p><div class="shop-grid">${Object.entries(data.items).map(([id,i])=>`<article class="shop-item"><h3>${i.icon} ${i.name}</h3><p>${i.ru}</p><button data-buy="${id}" ${state.coins<i.price?'disabled':''}>🪙 ${i.price}</button></article>`).join('')}</div>`;$$('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy))}
function buy(id){let item=data.items[id];if(state.coins<item.price)return;state.coins-=item.price;if(id==='sword')state.sword++;else if(id==='hint'){let locked=data.words.find(w=>!state.learned.includes(w.id));if(locked)learnWord(locked.es)}else{let inv=state.inventory.find(i=>i.id===id);inv?inv.qty++:state.inventory.push({id,qty:1})}toast(`${item.name} comprado`,item.icon);save();openShop();updateHud()}
function usePotion(){let inv=state.inventory.find(i=>i.id==='potion');if(!inv||!inv.qty)return;inv.qty--;state.hp=clamp(state.hp+45,0,state.maxHp);if(!inv.qty)state.inventory=state.inventory.filter(i=>i.qty);save();closeModal();toast('Vida recuperada · Здоровье восстановлено','❤️');updateHud()}
function updateHud(){$('#hud-name').textContent=state.name;$('#level-label').textContent=`Nv. ${state.level}`;$('#hp-fill').style.width=`${state.hp/state.maxHp*100}%`;$('#hp-text').textContent=`${Math.ceil(state.hp)} / ${state.maxHp}`;$('#mana-fill').style.width=`${state.mana/state.maxMana*100}%`;$('#mana-text').textContent=`${Math.floor(state.mana)} / ${state.maxMana}`;$('#coin-count').textContent=state.coins;$('#word-count').textContent=state.learned.length;let boss=entities.find(e=>e.boss&&!e.dead);$('#boss-bar').classList.toggle('hidden',!boss);if(boss){$('#boss-name').textContent=boss.name;$('#boss-fill').style.width=`${boss.hp/boss.maxHp*100}%`}}
function updateRegionUI(){let r=data.regions[state.region];$('#region-name').textContent=r.name;$('#region-theme').textContent=r.theme;$('.region-icon').textContent=r.icon;updateObjective()}
function updateObjective(){let text=state.quest==='meetOwl'?'Habla con Don Diccionario':state.quest==='killShadows'?`Derrota Sombras (${state.questKills}/3)`:state.quest==='boss'?'Viaja a la Aldea y derrota al Guardián':'Explora Verbalia';$('#objective-text').textContent=text}
function toast(text,icon='✨'){let e=document.createElement('div');e.className='toast';e.textContent=`${icon} ${text}`;$('#toast-zone').append(e);setTimeout(()=>e.remove(),3100)}
function togglePause(){if(!running||modalOpen||dialogueOpen)return;paused=!paused;$('#pause').classList.toggle('hidden',!paused)}
function startGame(saved=false){state=saved?load():freshState($('#hero-name').value.trim());if(!state)return;state.mana=state.mana??60;
 state.shadowKills=state.shadowKills??Math.max(state.questKills||0,state.quest==='killShadows'?Math.min(state.kills||0,3):0);
 state.questKills=Math.min(3,state.shadowKills);
 player=new Player;spawnRegion();running=true;
 if(state.quest==='killShadows'&&state.shadowKills>=3)completeShadowQuest();$('#welcome').classList.add('hidden');$('#hud').classList.remove('hidden');$('#objective').classList.remove('hidden');$('#game-nav').classList.remove('hidden');updateHud();save();toast(`¡Bienvenido, ${state.name}! · Добро пожаловать!`,'🦉')}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escapeRegex(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
let audioCtx;function sfx(freq,dur,type){if(!sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch{}}
// Entradas y botones
addEventListener('keydown',e=>{if(!keys[e.code])pressed.add(e.code);keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(dialogueOpen&&(e.code==='Enter'||e.code==='KeyE'||e.code==='Space')){e.preventDefault();nextDialogue()}if(dialogueOpen&&e.code==='KeyT')$('#dialogue-ru').classList.toggle('hidden');if(e.code==='Escape'){if(modalOpen)closeModal();else if(paused)togglePause()}});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('mousedown',()=>{if(running&&!paused&&!modalOpen&&!dialogueOpen)player.attack()});
$('#dialogue-next').onclick=nextDialogue;$('#translate-line').onclick=()=>$('#dialogue-ru').classList.toggle('hidden');$('#modal-close').onclick=closeModal;$('#modal-backdrop').onclick=e=>{if(e.target.id==='modal-backdrop')closeModal()};$('#start-btn').onclick=()=>{if(!$('#hero-name').value.trim()){toast('Escribe tu nombre · Напиши своё имя','✏️');$('#hero-name').focus();return}startGame(false)};$('#continue-btn').onclick=()=>startGame(true);$$('.hero-option').forEach(b=>b.onclick=()=>{$$('.hero-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedColor=b.dataset.color});$$('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));$$('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='resume')togglePause();if(b.dataset.action==='save')save(true);if(b.dataset.action==='magic')openMagic()});$('#sound-btn').onclick=()=>{sound=!sound;$('#sound-btn').textContent=sound?'♪':'×'};
if(load()){$('#continue-btn').classList.remove('hidden');$('#continue-btn').textContent=`CONTINUAR COMO ${load().name.toUpperCase()}`}
// Fondo animado aun antes de iniciar
state=freshState('Héroe');player=new Player;spawnRegion();requestAnimationFrame(loop);
})();
