(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const VW=960,VH=540,WORLD={w:1920,h:1280,tile:64},SAVE='valdoria_save_v1';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rand=(a,b)=>a+Math.random()*(b-a);
const keys={},pressed=new Set();let last=0,running=false,paused=false,panelOpen=false,dialogueOpen=false,sound=true,audioCtx;
const images={},sources={rpg:'assets/rpg-base.png',town:'assets/tiny-town.png',dungeon:'assets/tiny-dungeon.png',rogue:'assets/roguelike.png'};
const loadAssets=()=>Promise.all(Object.entries(sources).map(([id,src])=>new Promise(resolve=>{const image=new Image();image.onload=()=>{images[id]=image;resolve()};image.onerror=resolve;image.src=src})));
function rpg(index,x,y,w=64,h=64){const im=images.rpg;if(!im)return;ctx.drawImage(im,(index%20)*64,Math.floor(index/20)*64,64,64,Math.round(x),Math.round(y),w,h)}
function tiny(sheet,index,x,y,size=48,flip=false){const im=images[sheet];if(!im)return;ctx.save();if(flip){ctx.translate(x+size,y);ctx.scale(-1,1);ctx.drawImage(im,(index%12)*16,Math.floor(index/12)*16,16,16,0,0,size,size)}else ctx.drawImage(im,(index%12)*16,Math.floor(index/12)*16,16,16,Math.round(x),Math.round(y),size,size);ctx.restore()}
const stateDefault=name=>({name:name||'Aren',x:360,y:650,hp:100,maxHp:100,energy:70,maxEnergy:70,coins:0,crystals:0,quest:'talk',inventory:[{id:'potion',qty:1}],kills:0,bossDead:false,playtime:0});
let state=stateDefault('Aren'),player,camera={x:0,y:0},enemies=[],drops=[],particles=[],texts=[],nearNpc=null,currentDialogue=null,lineIndex=0;
const npcs=[
 {id:'lina',name:'Lina, la guardiana',portrait:'🛡️',sprite:87,x:430,y:520,lines:[['Hola, héroe. La Sombra ha robado tres cristales.'],['Busca los cristales en el valle. Después, ve a la cripta.']]},
 {id:'tomas',name:'Tomás',portrait:'🧑',sprite:85,x:650,y:720,lines:[['Hola. El bosque está al norte.'],['Ten cuidado. Hay monstruos entre los árboles.']]},
 {id:'merchant',name:'Bruno, el mercader',portrait:'🧔',sprite:88,x:300,y:820,lines:[['Bienvenido a mi tienda.'],['Una poción cuesta diez monedas.']]},
 {id:'sage',name:'Mara, la sabia',portrait:'🔮',sprite:84,x:1250,y:360,lines:[['La cripta está al este.'],['Necesitas tres cristales para romper el sello.']]}
];
const houses=[{x:220,y:380,type:0},{x:500,y:380,type:1},{x:220,y:780,type:1},{x:570,y:790,type:0}];
const trees=[];for(let i=0;i<44;i++){let x=80+(i*173)%1760,y=80+(i*257)%1120;if(x<780&&y>300&&y<920)continue;if(x>860&&x<1080&&!(y>555&&y<705))continue;trees.push({x,y,kind:i%3})}
const rocks=[];for(let i=0;i<20;i++)rocks.push({x:760+(i*197)%1050,y:100+(i*151)%1060});
const crystals=[{x:760,y:220,id:0},{x:1210,y:1030,id:1},{x:1580,y:240,id:2}];
function spawnEnemies(){enemies=[];const points=[[720,310],[810,900],[1120,250],[1180,780],[1370,990],[1500,700],[1700,900],[1050,1080]];points.forEach((p,i)=>enemies.push(new Enemy(p[0],p[1],i%3===0?109:108)));if(!state.bossDead)enemies.push(new Enemy(1640,480,111,true))}
class Player{constructor(){this.x=state.x;this.y=state.y;this.dir={x:1,y:0};this.speed=180;this.r=17;this.attackTime=0;this.attackCd=0;this.dash=0;this.dashCd=0;this.hurt=0;this.walk=0}
 update(dt){let dx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),dy=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0),moving=dx||dy;if(moving){let l=Math.hypot(dx,dy);dx/=l;dy/=l;this.dir={x:dx,y:dy};this.walk+=dt*10}let ox=this.x,oy=this.y,sp=this.speed*(this.dash>0?2.6:1);this.x+=dx*sp*dt;this.y+=dy*sp*dt;if(collides(this.x,this.y,this.r)){this.x=ox;this.y=oy}this.x=clamp(this.x,20,WORLD.w-20);this.y=clamp(this.y,20,WORLD.h-20);this.attackTime=Math.max(0,this.attackTime-dt);this.attackCd=Math.max(0,this.attackCd-dt);this.dash=Math.max(0,this.dash-dt);this.dashCd=Math.max(0,this.dashCd-dt);this.hurt=Math.max(0,this.hurt-dt);state.energy=clamp(state.energy+15*dt,0,state.maxEnergy);if(pressed.has('Space'))this.attack();if((pressed.has('ShiftLeft')||pressed.has('ShiftRight'))&&this.dashCd<=0&&state.energy>=15){state.energy-=15;this.dash=.18;this.dashCd=.75;burst(this.x,this.y,'#9ceeff',14);fx('dash')}if(moving&&Math.random()<dt*8)particles.push({x:this.x,y:this.y+14,vx:rand(-12,12),vy:rand(-25,-8),life:.35,color:'#d6be86',size:3})}
 attack(){if(this.attackCd>0)return;this.attackCd=.35;this.attackTime=.18;fx('sword');const hx=this.x+this.dir.x*38,hy=this.y+this.dir.y*38;enemies.forEach(e=>{if(!e.dead&&Math.hypot(e.x-hx,e.y-hy)<e.r+35)e.damage(28,this.dir)})}
 damage(amount){if(this.hurt>0||this.dash>0)return;state.hp-=amount;this.hurt=.7;shake=8;flash=.13;burst(this.x,this.y,'#ff667b',16);texts.push({x:this.x,y:this.y-28,text:`-${amount}`,color:'#ff8a98',life:.8});fx('hurt');if(state.hp<=0){state.hp=state.maxHp;state.coins=Math.max(0,state.coins-5);this.x=360;this.y=650;notice('Has vuelto a Villa Roble.','💔')}updateHud()}
 draw(){ctx.save();ctx.translate(this.x-camera.x,this.y-camera.y);const bob=Math.sin(this.walk)*2,flip=this.dir.x<0;if(this.hurt&&Math.floor(this.hurt*12)%2)ctx.globalAlpha=.35;ctx.fillStyle='#11172866';ctx.beginPath();ctx.ellipse(0,17,18,7,0,0,Math.PI*2);ctx.fill();tiny('dungeon',86,-23,-28+bob,46,flip);ctx.strokeStyle='#74d8f0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,1,23,0,Math.PI*2);if(state.energy===state.maxEnergy)ctx.stroke();if(this.attackTime>0){const a=Math.atan2(this.dir.y,this.dir.x),s=(.18-this.attackTime)/.18;ctx.rotate(a-.8+s*1.6);ctx.strokeStyle='#fff2ab55';ctx.lineWidth=15;ctx.beginPath();ctx.arc(0,0,40,-.5,.5);ctx.stroke();ctx.strokeStyle='#f9edce';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(17,0);ctx.lineTo(52,0);ctx.stroke();ctx.fillStyle='#e5b84f';ctx.fillRect(14,-6,6,12)}ctx.restore()}}
class Enemy{constructor(x,y,sprite,boss=false){Object.assign(this,{x,y,sprite,boss,r:boss?31:17,maxHp:boss?260:55,hp:boss?260:55,speed:boss?43:58,damageValue:boss?16:9,dead:false,hit:0,cool:0,shot:1})}
 update(dt){if(this.dead)return;this.hit=Math.max(0,this.hit-dt);this.cool-=dt;this.shot-=dt;let d=distance(this,player);if(this.boss&&state.crystals<3)return;if(d<340&&d>this.r+player.r){this.x+=(player.x-this.x)/d*this.speed*dt;this.y+=(player.y-this.y)/d*this.speed*dt}if(d<this.r+player.r+5&&this.cool<=0){player.damage(this.damageValue);this.cool=1}if(this.boss&&this.shot<=0&&d<500){this.shot=1.7;let a=Math.atan2(player.y-this.y,player.x-this.x);drops.push({type:'orb',x:this.x,y:this.y,vx:Math.cos(a)*170,vy:Math.sin(a)*170,life:4,damage:10});fx('magic')}}
 damage(n,dir){if(this.boss&&state.crystals<3){notice('El sello necesita tres cristales.','🔒');return}this.hp-=n;this.hit=.12;this.x+=dir.x*13;this.y+=dir.y*13;shake=this.boss?8:4;burst(this.x,this.y,'#ffd278',8);texts.push({x:this.x,y:this.y-this.r,text:`-${n}`,color:'#ffe189',life:.7});fx('hit');if(this.hp<=0)this.die()}
 die(){this.dead=true;state.kills++;let amount=this.boss?35:rand(2,6)|0;for(let i=0;i<amount;i++)drops.push({type:'coin',x:this.x,y:this.y,vx:rand(-90,90),vy:rand(-130,-50),life:7,delay:rand(.2,.6)});burst(this.x,this.y,this.boss?'#d89cff':'#f5c958',this.boss?30:12);if(this.boss){state.bossDead=true;state.quest='complete';setTimeout(()=>$('#victory').classList.remove('hidden'),900);fx('victory')}save()}
 draw(){if(this.dead)return;let x=this.x-camera.x,y=this.y-camera.y;if(x<-60||y<-60||x>VW+60||y>VH+60)return;ctx.save();ctx.translate(x,y);if(this.hit)ctx.globalAlpha=.5;ctx.fillStyle='#11142466';ctx.beginPath();ctx.ellipse(0,this.r*.65,this.r,7,0,0,Math.PI*2);ctx.fill();tiny('dungeon',this.sprite,-this.r,-this.r,this.r*2,this.x<player.x);if(this.boss){ctx.strokeStyle=state.crystals<3?'#7599c8':'#d89cff';ctx.lineWidth=3;ctx.setLineDash([6,5]);ctx.beginPath();ctx.arc(0,0,this.r+7+Math.sin(performance.now()/200)*2,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}ctx.restore();if(!this.boss&&this.hp<this.maxHp){ctx.fillStyle='#151525';ctx.fillRect(x-18,y-this.r-10,36,5);ctx.fillStyle='#e95468';ctx.fillRect(x-18,y-this.r-10,36*this.hp/this.maxHp,5)}}}
function collides(x,y,r){if(x-r<0||y-r<0||x+r>WORLD.w||y+r>WORLD.h)return true;const river=x+r>900&&x-r<1028,bridge=y>570&&y<690;if(river&&!bridge)return true;for(const h of houses)if(x+r>h.x&&x-r<h.x+192&&y+r>h.y&&y-r<h.y+125)return true;if(x>1430&&x<1480&&y>360&&y<600&&state.crystals<3)return true;return trees.some(t=>Math.hypot(x-t.x,y-(t.y+15))<r+18)}
function drawGround(){const ts=64,minX=Math.floor(camera.x/ts)*ts,minY=Math.floor(camera.y/ts)*ts;for(let y=minY;y<camera.y+VH+ts;y+=ts)for(let x=minX;x<camera.x+VW+ts;x+=ts){let id=((x/ts+y/ts)%5===0)?4:3;if(x>=900&&x<1028)id=14;if(y>=600&&y<690)id=8;if(x>1420&&y<760)id=60;rpg(id,x-camera.x,y-camera.y,64,64)}// caminos secundarios
 ctx.globalAlpha=.42;for(let x=180;x<760;x+=64)rpg(8,x-camera.x,520-camera.y,64,64);for(let y=460;y<920;y+=64)rpg(8,410-camera.x,y-camera.y,64,64);ctx.globalAlpha=1}
function drawHouse(h){let x=h.x-camera.x,y=h.y-camera.y;if(x<-230||x>VW+30||y<-180||y>VH+30)return;ctx.fillStyle='#10142166';ctx.beginPath();ctx.ellipse(x+96,y+127,104,18,0,0,Math.PI*2);ctx.fill();for(let row=0;row<2;row++)for(let col=0;col<4;col++)tiny('town',h.type?52:49,x+col*48,y+29+row*48,48);for(let col=0;col<4;col++)tiny('town',62,x+col*48,y-18,48);tiny('town',h.type?85:86,x+72,y+77,48);tiny('town',84,x+15,y+56,48);tiny('town',88,x+129,y+56,48);ctx.fillStyle='#f2ca58';ctx.fillRect(x+65,y+31,62,7);ctx.fillStyle='#5a382d';ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillText(h.type?'POSADA':'CASA',x+96,y+38);ctx.textAlign='left'}
function drawCastle(){let x=1460-camera.x,y=250-camera.y;ctx.fillStyle='#10132177';ctx.beginPath();ctx.ellipse(x+180,y+300,220,26,0,0,Math.PI*2);ctx.fill();for(let row=0;row<5;row++)for(let col=0;col<7;col++)tiny('town',49,x+col*48,y+45+row*48,48);for(const tx of [x-48,x+288])for(let row=0;row<6;row++)tiny('town',49,tx,y+row*48,48);for(let col=-1;col<8;col++)tiny('town',62,x+col*48,y-45,48);tiny('town',73,x+144,y+237,48);tiny('town',84,x+40,y+125,48);tiny('town',84,x+248,y+125,48);ctx.fillStyle='#a43751';ctx.fillRect(x+174,y-72,5,85);ctx.beginPath();ctx.moveTo(x+179,y-68);ctx.lineTo(x+228,y-53);ctx.lineTo(x+179,y-34);ctx.fill();ctx.fillStyle='#f4cf63';ctx.font='bold 15px serif';ctx.fillText('V',x+193,y-48)}
function drawBridge(){let x=900-camera.x,y=570-camera.y;ctx.fillStyle='#543625';ctx.fillRect(x,y,128,120);for(let yy=5;yy<120;yy+=18){ctx.fillStyle=yy%36?'#b47742':'#936037';ctx.fillRect(x, y+yy,128,15);ctx.fillStyle='#e1ad6a55';ctx.fillRect(x+4,y+yy+2,120,2)}ctx.fillStyle='#3f2d25';ctx.fillRect(x,y,7,120);ctx.fillRect(x+121,y,7,120)}
function drawTree(t){let x=t.x-camera.x,y=t.y-camera.y;if(x<-90||y<-100||x>VW+90||y>VH+80)return;ctx.fillStyle='#10172155';ctx.beginPath();ctx.ellipse(x,y+30,31,11,0,0,Math.PI*2);ctx.fill();rpg([175,177,179][t.kind],x-40,y-55,80,80)}
function drawRock(r){let x=r.x-camera.x,y=r.y-camera.y;ctx.fillStyle='#171a2155';ctx.beginPath();ctx.ellipse(x,y+8,18,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#687477';ctx.beginPath();ctx.moveTo(x-17,y+6);ctx.lineTo(x-10,y-12);ctx.lineTo(x+7,y-17);ctx.lineTo(x+18,y+7);ctx.closePath();ctx.fill();ctx.fillStyle='#a7afaa';ctx.beginPath();ctx.moveTo(x-8,y-10);ctx.lineTo(x+6,y-14);ctx.lineTo(x,y-5);ctx.fill()}
function drawCrystal(c){if(state[`crystal${c.id}`])return;let x=c.x-camera.x,y=c.y-camera.y,b=Math.sin(performance.now()/250+c.id)*5;ctx.save();ctx.translate(x,y+b);ctx.shadowColor='#80efff';ctx.shadowBlur=18;ctx.fillStyle='#68dff2';ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(13,0);ctx.lineTo(0,22);ctx.lineTo(-13,0);ctx.fill();ctx.fillStyle='#e4ffff';ctx.beginPath();ctx.moveTo(0,-17);ctx.lineTo(4,-1);ctx.lineTo(-3,8);ctx.fill();ctx.restore()}
function drawNpc(n){let x=n.x-camera.x,y=n.y-camera.y,b=Math.sin(performance.now()/380+n.x)*2;ctx.fillStyle='#11142455';ctx.beginPath();ctx.ellipse(x,y+17,17,6,0,0,Math.PI*2);ctx.fill();tiny('dungeon',n.sprite,x-22,y-28+b,44);ctx.font='bold 10px sans-serif';let w=clamp(ctx.measureText(n.name).width+16,62,150),cx=clamp(x,w/2+4,VW-w/2-4);ctx.fillStyle='#151326dc';ctx.beginPath();ctx.roundRect(cx-w/2,y+24,w,17,6);ctx.fill();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText(n.name,cx,y+36,w-10);ctx.textAlign='left'}
let shake=0,flash=0;function drawWorld(t){ctx.save();if(shake>0)ctx.translate(rand(-shake,shake),rand(-shake,shake));drawGround();houses.forEach(drawHouse);drawCastle();drawBridge();rocks.forEach(drawRock);trees.sort((a,b)=>a.y-b.y).forEach(drawTree);crystals.forEach(drawCrystal);const actors=[...npcs.map(n=>({y:n.y,draw:()=>drawNpc(n)})),...enemies.map(e=>({y:e.y,draw:()=>e.draw()})),{y:player.y,draw:()=>player.draw()}].sort((a,b)=>a.y-b.y);actors.forEach(a=>a.draw());drops.forEach(drawDrop);particles.forEach(drawParticle);texts.forEach(drawText);ctx.restore();if(flash>0){ctx.globalAlpha=flash*4;ctx.fillStyle='#fff1cc';ctx.fillRect(0,0,VW,VH);ctx.globalAlpha=1}}
function drawDrop(d){let x=d.x-camera.x,y=d.y-camera.y;if(d.type==='coin'){ctx.fillStyle='#ffd353';ctx.shadowColor='#ffd353';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}else{ctx.fillStyle='#9b66c4';ctx.shadowColor='#bd83e8';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}}
function drawParticle(p){ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x-camera.x,p.y-camera.y,p.size||4,p.size||4);ctx.globalAlpha=1}function drawText(f){ctx.globalAlpha=clamp(f.life*2,0,1);ctx.font='bold 14px monospace';ctx.textAlign='center';ctx.strokeStyle='#171323';ctx.lineWidth=4;ctx.strokeText(f.text,f.x-camera.x,f.y-camera.y);ctx.fillStyle=f.color;ctx.fillText(f.text,f.x-camera.x,f.y-camera.y);ctx.textAlign='left';ctx.globalAlpha=1}function burst(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-90,90),vy:rand(-100,40),life:rand(.35,.8),color,size:rand(2,5)})}
function updateDrops(dt){drops.forEach(d=>{d.life-=dt;if(d.type==='orb'){d.x+=d.vx*dt;d.y+=d.vy*dt;if(distance(d,player)<22){player.damage(d.damage);d.life=0}}else{if(d.delay>0){d.delay-=dt;d.x+=d.vx*dt;d.y+=d.vy*dt;d.vy+=220*dt}else{let dx=player.x-d.x,dy=player.y-d.y,l=Math.max(1,Math.hypot(dx,dy));d.x+=dx/l*260*dt;d.y+=dy/l*260*dt;if(l<20){state.coins++;d.life=0;fx('coin')}}}});drops=drops.filter(d=>d.life>0)}
function update(dt){if(!running||paused||panelOpen||dialogueOpen)return;state.playtime+=dt;shake=Math.max(0,shake-dt*28);flash=Math.max(0,flash-dt);player.update(dt);enemies.forEach(e=>e.update(dt));updateDrops(dt);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);texts.forEach(f=>{f.y-=25*dt;f.life-=dt});texts=texts.filter(f=>f.life>0);nearNpc=npcs.filter(n=>distance(n,player)<65).sort((a,b)=>distance(a,player)-distance(b,player))[0]||null;for(const c of crystals){if(!state[`crystal${c.id}`]&&distance(c,player)<28)collectCrystal(c)}if((pressed.has('KeyE')||pressed.has('Enter'))&&nearNpc)interact(nearNpc);if(pressed.has('KeyJ'))openPanel('quest');if(pressed.has('KeyI'))openPanel('inventory');if(pressed.has('KeyM'))openPanel('map');camera.x=clamp(player.x-VW/2,0,WORLD.w-VW);camera.y=clamp(player.y-VH/2,0,WORLD.h-VH);updateHud()}
function collectCrystal(c){state[`crystal${c.id}`]=true;state.crystals++;burst(c.x,c.y,'#7cefff',25);fx('crystal');notice(`Cristal encontrado: ${state.crystals}/3`,'💎');if(state.crystals>=3){state.quest='boss';notice('El sello de la cripta está roto.','🔓')}save()}
function interact(n){if(n.id==='merchant'){startDialogue(n,()=>openShop());return}startDialogue(n,()=>{if(n.id==='lina'&&state.quest==='talk'){state.quest='crystals';notice('Nueva misión: busca tres cristales.','📜');save()}})}
function startDialogue(n,after){currentDialogue={n,after};lineIndex=0;dialogueOpen=true;$('#action-bar').classList.add('hidden');$('#dialogue').classList.remove('hidden');showLine()}function showLine(){let n=currentDialogue.n;$('#portrait').textContent=n.portrait;$('#speaker').textContent=n.name;$('#line').textContent=n.lines[lineIndex][0];fx('talk')}function nextLine(){if(!currentDialogue)return;if(++lineIndex<currentDialogue.n.lines.length)showLine();else{let cb=currentDialogue.after;dialogueOpen=false;currentDialogue=null;$('#dialogue').classList.add('hidden');$('#action-bar').classList.remove('hidden');if(cb)cb()}}
function openShop(){panelOpen=true;$('#panel-backdrop').classList.remove('hidden');$('#panel-kicker').textContent='TIENDA';$('#panel-title').textContent='Mercado de Bruno';$('#panel-content').innerHTML=`<div class="panel-card"><h3>🧪 Poción de vida</h3><p>Recupera 50 puntos de vida.</p><button id="buy-potion" ${state.coins<10?'disabled':''}>Comprar · 🪙 10</button></div>`;$('#buy-potion').onclick=()=>{if(state.coins<10)return;state.coins-=10;let item=state.inventory.find(i=>i.id==='potion');item?item.qty++:state.inventory.push({id:'potion',qty:1});fx('coin');notice('Poción comprada.','🧪');save();closePanel()}}
function openPanel(kind){panelOpen=true;$('#panel-backdrop').classList.remove('hidden');const c=$('#panel-content');if(kind==='quest'){ $('#panel-kicker').textContent='DIARIO';$('#panel-title').textContent='Misión actual';let info={talk:['Habla con Lina','La guardiana está en Villa Roble.'],crystals:['Busca tres cristales',`Cristales encontrados: ${state.crystals}/3`],boss:['Derrota al Señor de la Cripta','La cripta está al este del río.'],complete:['Valdoria está a salvo','Puedes seguir explorando.']}[state.quest];c.innerHTML=`<article class="panel-card"><h3>${info[0]}</h3><p>${info[1]}</p></article>`}if(kind==='inventory'){$('#panel-kicker').textContent='EQUIPO';$('#panel-title').textContent='Mochila';c.innerHTML=`<div class="inventory">${state.inventory.map(i=>`<article class="panel-card"><div class="icon">🧪</div><strong>Poción</strong><p>× ${i.qty}</p><button data-use="${i.id}">Usar</button></article>`).join('')||'<p>La mochila está vacía.</p>'}</div>`;$$('[data-use]').forEach(b=>b.onclick=()=>usePotion())}if(kind==='map'){ $('#panel-kicker').textContent='VALDORIA';$('#panel-title').textContent='Mapa del valle';c.innerHTML=`<div class="panel-card"><svg viewBox="0 0 600 260" class="map-svg"><rect width="600" height="260" rx="12" fill="#426f43"/><path d="M0 135 Q170 105 285 145 T600 130" stroke="#b98b52" stroke-width="28" fill="none"/><path d="M305 0 V260" stroke="#3d9ab2" stroke-width="42"/><rect x="55" y="75" width="145" height="90" fill="#c87855"/><rect x="445" y="50" width="110" height="120" fill="#555267"/><circle cx="${player.x/WORLD.w*600}" cy="${player.y/WORLD.h*260}" r="8" fill="#ffe268" stroke="#342743" stroke-width="4"/><text x="75" y="70" fill="white">Villa Roble</text><text x="442" y="42" fill="white">Cripta</text></svg></div>`}}
function closePanel(){panelOpen=false;$('#panel-backdrop').classList.add('hidden')}function usePotion(){let i=state.inventory.find(x=>x.id==='potion');if(!i||i.qty<1)return;i.qty--;state.hp=clamp(state.hp+50,0,state.maxHp);if(!i.qty)state.inventory=state.inventory.filter(x=>x.qty);notice('Vida recuperada.','❤️');fx('crystal');save();closePanel();updateHud()}
function updateHud(){$('#hero-name').textContent=state.name;$('#health-fill').style.width=`${state.hp/state.maxHp*100}%`;$('#health-text').textContent=`${Math.ceil(state.hp)} / ${state.maxHp}`;$('#energy-fill').style.width=`${state.energy/state.maxEnergy*100}%`;$('#coins').textContent=state.coins;$('#crystals').textContent=`${state.crystals}/3`;let zone=player.x<850?'Villa Roble':player.x<1400?'Bosque del Río':'Cripta Antigua';$('#zone-name').textContent=zone;$('#chapter').textContent=state.quest==='complete'?'EPÍLOGO':'CAPÍTULO I';$('#quest-short').textContent={talk:'Habla con la guardiana',crystals:'Busca los tres cristales',boss:'Entra en la cripta',complete:'Valdoria está a salvo'}[state.quest];let boss=enemies.find(e=>e.boss&&!e.dead);$('#boss-hud').classList.toggle('hidden',!boss||state.crystals<3);if(boss)$('#boss-fill').style.width=`${boss.hp/boss.maxHp*100}%`}
function notice(text,icon='✨'){let el=document.createElement('div');el.className='notice';el.textContent=`${icon} ${text}`;$('#notice-zone').append(el);setTimeout(()=>el.remove(),3100)}function save(){state.x=player.x;state.y=player.y;localStorage.setItem(SAVE,JSON.stringify(state))}function load(){try{return JSON.parse(localStorage.getItem(SAVE))}catch{return null}}
function tone(freq,dur=.1,type='sine',vol=.025,delay=0){if(!sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+delay;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+dur)}catch{}}function fx(id){({sword:()=>{tone(190,.07,'square');tone(500,.08,'triangle',.015,.03)},hit:()=>tone(110,.1,'square'),hurt:()=>tone(90,.18,'sawtooth'),dash:()=>tone(360,.13,'sine'),magic:()=>tone(520,.2,'sine'),coin:()=>{tone(900,.07,'square');tone(1300,.1,'square',.02,.07)},crystal:()=>[520,660,790,1040].forEach((f,i)=>tone(f,.22,'triangle',.025,i*.06)),talk:()=>tone(430,.05,'square',.01),victory:()=>[392,523,659,784,1047].forEach((f,i)=>tone(f,.35,'triangle',.025,i*.1))}[id]||(()=>{}))()}
function startGame(saved=false){state=saved?load():stateDefault($('#name-input').value.trim());if(!state)return;state.energy??=70;player=new Player;spawnEnemies();camera.x=clamp(player.x-VW/2,0,WORLD.w-VW);camera.y=clamp(player.y-VH/2,0,WORLD.h-VH);running=true;$('#start-screen').classList.add('hidden');$('#hud').classList.remove('hidden');$('#action-bar').classList.remove('hidden');updateHud();save();notice(`Bienvenido, ${state.name}.`,'⚔️')}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(running)update(dt);drawWorld(t);pressed.clear();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{if(!keys[e.code])pressed.add(e.code);keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(dialogueOpen&&(e.code==='KeyE'||e.code==='Enter'||e.code==='Space'))nextLine();if(e.code==='Escape'){if(panelOpen)closePanel();else paused=!paused}});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('mousedown',()=>running&&!panelOpen&&!dialogueOpen&&player.attack());$('#dialogue-next').onclick=nextLine;$('#panel-close').onclick=closePanel;$('#panel-backdrop').onclick=e=>e.target.id==='panel-backdrop'&&closePanel();$$('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$('#start').onclick=()=>startGame(false);$('#continue').onclick=()=>startGame(true);$('#victory-close').onclick=()=>$('#victory').classList.add('hidden');$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'♫':'×'};if(load())$('#continue').classList.remove('hidden');
loadAssets().then(()=>{player=new Player;spawnEnemies();requestAnimationFrame(loop)});
})();
